# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web001" do |web001|
    web001.vm.box = "ubuntu/trusty64"
    web001.vm.hostname = "web001"
    web001.vm.network "private_network", ip: "192.168.255.101"
    web001.vm.provision "chef_solo" do |chef|
      chef.add_recipe "simple_web"
    end
  end
  config.vm.define "web002" do |web002|
    web002.vm.box = "ubuntu/trusty64"
    web002.vm.hostname = "web002"
  end
end
